<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-08T17:48:50 IST" name="Suite" finished-at="2024-12-08T17:49:15 IST" duration-ms="24303">
    <groups>
      <group name="purchase">
        <method signature="StandloonTest.submitOrder(java.util.HashMap)[pri:0, instance:gty.selum.StandloonTest@123ef382]" name="submitOrder" class="gty.selum.StandloonTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-12-08T17:48:50 IST" name="Submit Test" finished-at="2024-12-08T17:48:50 IST" duration-ms="25">
      <class name="gty.selum.StandloonTest">
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:gty.selum.StandloonTest@123ef382]" started-at="2024-12-08T17:48:50 IST" name="submitOrder" data-provider="GetData" finished-at="2024-12-08T17:48:50 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
at gty.selum.BaseTest.getDataToMap(BaseTest.java:45)
at gty.selum.StandloonTest.GetData(StandloonTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 29 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
... 36 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- gty.selum.StandloonTest -->
    </test> <!-- Submit Test -->
    <test started-at="2024-12-08T17:48:50 IST" name="Error Test" finished-at="2024-12-08T17:49:15 IST" duration-ms="24245">
      <class name="gty.selum.Errorvalidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:gty.selum.Errorvalidation@293a5bf6]" started-at="2024-12-08T17:48:50 IST" name="launchApplication" finished-at="2024-12-08T17:48:57 IST" duration-ms="6252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginEroor()[pri:0, instance:gty.selum.Errorvalidation@293a5bf6]" started-at="2024-12-08T17:48:57 IST" name="loginEroor" finished-at="2024-12-08T17:48:57 IST" duration-ms="501" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginEroor -->
        <test-method is-config="true" signature="closet()[pri:0, instance:gty.selum.Errorvalidation@293a5bf6]" started-at="2024-12-08T17:48:57 IST" name="closet" finished-at="2024-12-08T17:48:57 IST" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closet -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:gty.selum.Errorvalidation@293a5bf6]" started-at="2024-12-08T17:48:57 IST" name="launchApplication" finished-at="2024-12-08T17:49:01 IST" duration-ms="3558" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:gty.selum.Errorvalidation@293a5bf6]" started-at="2024-12-08T17:49:01 IST" name="submitOrder" finished-at="2024-12-08T17:49:14 IST" duration-ms="13689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closet()[pri:0, instance:gty.selum.Errorvalidation@293a5bf6]" started-at="2024-12-08T17:49:14 IST" name="closet" finished-at="2024-12-08T17:49:15 IST" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closet -->
      </class> <!-- gty.selum.Errorvalidation -->
    </test> <!-- Error Test -->
  </suite> <!-- Suite -->
</testng-results>
